FROM node:18.16.1-alpine AS builder

# Change directory so that our commands run inside this new directory
WORKDIR /dist/src/app
COPY . /dist/src/app
RUN npm cache clean --force
RUN npm install @angular/cli@16.1.4 -g
RUN npm install
RUN ng build --base-href /editor-frontend/

# Stage 2: Install Nginx, Copy files and Expose Port
FROM nginx:latest AS ngi
EXPOSE 4201
#Copy nginx config
COPY ./nginx/nginx.config /etc/nginx/conf.d/default.conf
# Copying compiled code and nginx config to different folder
# NOTE: This path may change according to your project's output folder
COPY --from=builder /dist/src/app/dist/frontend /usr/share/nginx/html

